env:
  browser: true

extends:
  - plugin:react/recommended

parserOptions:
  sourceType: module

settings:
  react:
    version: detect

globals:
  VERSION: readonly
  think: readonly

rules:
  reactdisplay-name: off
  react/prop-types: off
