name: 'issue translator'
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  # discussion:
  #   types: [created, edited]
  # discussion_comment:
  #   types: [created, edited]

jobs:
  translate:
    permissions:
      issues: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lizheming/issues-translate-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          IS_MODIFY_TITLE: true
          APPEND_TRANSLATION: true
