name: 'publish @waline/client'

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/release-client.yml
      - packages/client/**
      - docs/**

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Client
        run: pnpm client:build

      - name: Publish NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/client

      - name: Build Docs
        run: |-
          pnpm docs:build
          > docs/src/.vuepress/dist/.nojekyll

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        if: steps.changed-docs.outputs.changed == 'true'
        with:
          branch: gh-pages
          folder: docs/src/.vuepress/dist
          ssh-key: ${{ secrets.SSH_TOKEN }}
          repository-name: walinejs/walinejs.github.io
